const RES=window.RES||[], MATERIALS=window.MATERIALS||[], PLAYBOOKS=window.PLAYBOOKS||[], COUNTRIES=window.COUNTRIES||[], STAGES=window.STAGES||[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], uniq=a=>[...new Set(a.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));
const state={favorites:new Set(JSON.parse(localStorage.getItem('gbo-favs')||'[]')), compare:[], search:'', filters:{cat:'',type:'',region:'',stage:'',scale:''}, countryRegion:''};
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function domain(u){try{return new URL(u).hostname.replace(/^www\./,'')}catch{return ''}}
function logoUrl(r){return `https://www.google.com/s2/favicons?domain_url=${encodeURIComponent(r.url)}&sz=128`}
function saveFav(){localStorage.setItem('gbo-favs',JSON.stringify([...state.favorites]))}
function showView(id){$$('.section').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$$('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===id));if(innerWidth<780)$('#side').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
function rcard(r){const fav=state.favorites.has(r.name), cmp=state.compare.includes(r.name);return `<article class="card"><button class="favstar ${fav?'on':''}" data-fav="${esc(r.name)}">★</button><div class="rhead"><div class="logo"><img src="${logoUrl(r)}" alt="" onerror="this.style.display='none';this.nextElementSibling.style.display='block'"><span style="display:none">${esc(r.name.slice(0,2).toUpperCase())}</span></div><div><h3>${esc(r.name)}</h3><div class="rmeta">${esc(r.type)} · ${esc(r.category)} · Etapa ${esc(r.stage)}</div></div></div><p class="desc">${esc(r.desc)}</p><div class="sourceTag">● Dominio oficial: ${esc(domain(r.url))}</div><div class="cardBtns"><button class="btn gold" data-open="${esc(r.name)}">Ficha</button><a class="btn" href="${esc(r.url)}" target="_blank" rel="noopener">Sitio oficial ↗</a><button class="btn ${cmp?'gold':''}" data-compare="${esc(r.name)}">${cmp?'Comparando':'Comparar'}</button></div></article>`}
function bindCards(){$$('[data-open]').forEach(b=>b.onclick=()=>openDetail(b.dataset.open));$$('[data-fav]').forEach(b=>b.onclick=()=>{const n=b.dataset.fav;state.favorites.has(n)?state.favorites.delete(n):state.favorites.add(n);saveFav();renderAll()});$$('[data-compare]').forEach(b=>b.onclick=()=>toggleCompare(b.dataset.compare))}
function openDetail(name){const r=RES.find(x=>x.name===name);if(!r)return;$('#modal').innerHTML=`<button class="btn close" id="closeModal">Cerrar ×</button><div class="rhead"><div class="logo"><img src="${logoUrl(r)}" alt=""></div><div><div class="eyebrow">${esc(r.type)} · ETAPA ${esc(r.stage)}</div><h1 style="font-size:26px;margin:5px 0">${esc(r.name)}</h1><div class="muted">${esc(r.company)} · ${esc(r.origin||'Origen no especificado')}</div></div></div><p>${esc(r.desc)}</p><div class="detailGrid"><div class="detail"><small>Categoría</small>${esc(r.category)}</div><div class="detail"><small>Región</small>${esc(r.region)}</div><div class="detail"><small>Países / cobertura</small>${esc(r.countries)}</div><div class="detail"><small>Tamaño recomendado</small>${esc(r.scale)}</div><div class="detail"><small>Nivel</small>${esc(r.level)}</div><div class="detail"><small>Última catalogación</small>${esc(r.verified)}</div></div><div class="notice">La presencia de un recurso en el catálogo no equivale a recomendación universal. Verifica disponibilidad, términos, precios, requisitos y regulación en su sitio oficial.</div><div class="toolbar" style="margin-top:14px"><a class="btn gold" target="_blank" rel="noopener" href="${esc(r.url)}">Abrir sitio oficial ↗</a>${r.docs?`<a class="btn" target="_blank" rel="noopener" href="${esc(r.docs)}">Documentación / ayuda ↗</a>`:''}<button class="btn" id="modalFav">${state.favorites.has(r.name)?'Quitar favorito':'Guardar favorito'}</button></div>`;$('#modalBack').classList.add('show');$('#closeModal').onclick=closeModal;$('#modalFav').onclick=()=>{state.favorites.has(r.name)?state.favorites.delete(r.name):state.favorites.add(r.name);saveFav();closeModal();renderAll()}}
function closeModal(){$('#modalBack').classList.remove('show')}
function toggleCompare(name){const i=state.compare.indexOf(name);if(i>=0)state.compare.splice(i,1);else if(state.compare.length<4)state.compare.push(name);else return alert('Puedes comparar hasta 4 recursos.');renderAll()}
function openCompare(){const rs=state.compare.map(n=>RES.find(r=>r.name===n)).filter(Boolean);if(!rs.length)return;$('#modal').innerHTML=`<button class="btn close" id="closeModal">Cerrar ×</button><div class="eyebrow">COMPARADOR</div><h1 style="font-size:24px">Comparación por función y cobertura</h1><div class="tableWrap"><table><thead><tr><th>Criterio</th>${rs.map(r=>`<th>${esc(r.name)}</th>`).join('')}</tr></thead><tbody>${[['Tipo','type'],['Categoría','category'],['Etapa','stage'],['Región','region'],['Cobertura','countries'],['Escala','scale'],['Nivel','level'],['Origen','origin']].map(([l,k])=>`<tr><td><b>${l}</b></td>${rs.map(r=>`<td>${esc(r[k])}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="muted small">La comparación no decide por ti: valida costos, soporte, restricciones de país, integraciones y condiciones comerciales en la fuente oficial.</p>`;$('#modalBack').classList.add('show');$('#closeModal').onclick=closeModal}
function fillSelect(id,vals,label){const e=$(id);e.innerHTML=`<option value="">${label}</option>`+vals.map(v=>`<option>${esc(v)}</option>`).join('');e.onchange=()=>{const key={fCat:'cat',fType:'type',fRegion:'region',fStage:'stage',fScale:'scale'}[e.id];state.filters[key]=e.value;renderCatalog()}}
function matchRegion(r,reg){if(!reg)return true;return r.region.includes(reg)||r.countries.includes(reg)}
function filtered(){let a=RES;const q=state.search.trim().toLowerCase();if(q)a=a.filter(r=>Object.values(r).join(' ').toLowerCase().includes(q));const f=state.filters;if(f.cat)a=a.filter(r=>r.category===f.cat);if(f.type)a=a.filter(r=>r.type===f.type);if(f.region)a=a.filter(r=>matchRegion(r,f.region));if(f.stage)a=a.filter(r=>r.stage===f.stage);if(f.scale)a=a.filter(r=>r.scale===f.scale);return a}
function renderCatalog(){const a=filtered();$('#catalogGrid').innerHTML=a.length?a.map(rcard).join(''):`<div class="empty">No se encontraron recursos con esos filtros.</div>`;$('#resultCount').textContent=`${a.length} resultados`;bindCards()}
function renderStats(){const official=RES.filter(r=>r.type.includes('Fuente')).length;const cats=uniq(RES.map(r=>r.category)).length;$('#stats').innerHTML=[[RES.length,'recursos catalogados'],[official,'fuentes oficiales/institucionales'],[COUNTRIES.length,'jurisdicciones guía'],[cats,'categorías funcionales'],['21/08/2026','revisión del catálogo']].map(x=>`<div class="stat"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('')}
const quickNames=['ChatGPT','Google Trends','Shopify','Amazon','Alibaba.com','Mercado Libre','Stripe','PayPal','DHL','HubSpot','n8n','Notion','Canva','Google Analytics','Semrush','GitHub','Vercel','SUNAT','World Trade Organization (WTO)','World Bank'];
function renderQuick(){const a=quickNames.map(n=>RES.find(r=>r.name===n)).filter(Boolean);$('#quick').innerHTML=a.map(r=>`<button class="q" data-open="${esc(r.name)}"><img src="${logoUrl(r)}" alt=""><b>${esc(r.name)}</b></button>`).join('');$$('.q[data-open]').forEach(b=>b.onclick=()=>openDetail(b.dataset.open))}
function renderOfficialHome(){const a=RES.filter(r=>r.type==='Fuente oficial').slice(0,8);$('#officialHome').innerHTML=a.map(rcard).join('');bindCards()}
const intents=[['Crear una empresa','Constitución, impuestos, marca y fuentes oficiales','Constitución de empresas'],['Encontrar proveedores','Sourcing, marketplaces B2B y evaluación','Sourcing / Marketplace'],['Importar productos','Comercio internacional, aduanas y logística','Comercio internacional'],['Vender online','E-commerce, marketplaces, pagos y marketing','E-commerce'],['Hacer publicidad','Google, Meta, TikTok, SEO y analítica','Publicidad'],['Automatizar operaciones','n8n, Make, Zapier, APIs y flujos','Automatización'],['Usar IA en la empresa','Investigación, análisis, contenido y desarrollo','Inteligencia artificial'],['Expandirme al extranjero','Fuentes por país, pagos, logística y marketplaces','Fuentes oficiales']];
function renderIntents(){$('#intents').innerHTML=intents.map(([a,b,c])=>`<button class="intent" data-intent="${esc(c)}"><b>${esc(a)}</b><span class="muted">${esc(b)}</span></button>`).join('');$$('[data-intent]').forEach(b=>b.onclick=()=>{showView('catalog');state.filters.cat=b.dataset.intent;$('#fCat').value=state.filters.cat;renderCatalog()})}
function renderCountries(){const reg=state.countryRegion;const a=COUNTRIES.filter(c=>!reg||c[1]===reg||c[1].includes(reg));$('#countryGrid').innerHTML=a.map(c=>`<div class="country"><div class="eyebrow">${esc(c[1])}</div><h3>${esc(c[0])}</h3><dl><dt>Constitución</dt><dd>${esc(c[2])}</dd><dt>Tributación</dt><dd>${esc(c[3])}</dd><dt>Propiedad IP</dt><dd>${esc(c[4])}</dd><dt>Aduanas</dt><dd>${esc(c[5])}</dd><dt>Datos</dt><dd>${esc(c[6])}</dd></dl><button class="btn" data-country="${esc(c[0])}">Ver recursos relacionados</button></div>`).join('');$$('[data-country]').forEach(b=>b.onclick=()=>{showView('catalog');state.search=b.dataset.country;$('#search').value=state.search;renderCatalog()})}
function renderRegionChips(){const regs=uniq(COUNTRIES.map(c=>c[1].split(' / ')[0]));$('#regionChips').innerHTML=`<button class="chip ${!state.countryRegion?'active':''}" data-cr="">Todos</button>`+regs.map(r=>`<button class="chip ${state.countryRegion===r?'active':''}" data-cr="${esc(r)}">${esc(r)}</button>`).join('');$$('[data-cr]').forEach(b=>b.onclick=()=>{state.countryRegion=b.dataset.cr;renderRegionChips();renderCountries()})}
function renderPlaybooks(){$('#playbookList').innerHTML=PLAYBOOKS.map(p=>`<div class="playbook"><div class="eyebrow">PLAYBOOK</div><h3>${esc(p[0])}</h3><p class="muted">${esc(p[1])}</p><ol>${p[2].map(s=>`<li>${esc(s)}</li>`).join('')}</ol></div>`).join('')}
function renderMaterials(){$('#materialGrid').innerHTML=MATERIALS.map(m=>`<div class="material"><small>${esc(m[1])}</small><h3>${esc(m[0])}</h3><div class="muted small">${esc(m[2])}</div></div>`).join('')}
function renderStages(){$('#stageList').innerHTML=STAGES.map(s=>`<div class="stageCard"><span>ETAPA ${s[0]}</span><b>${esc(s[1])}</b></div>`).join('')}
function renderFavs(){const a=RES.filter(r=>state.favorites.has(r.name));$('#favGrid').innerHTML=a.length?a.map(rcard).join(''):`<div class="empty">Todavía no has guardado recursos. Usa ★ en cualquier ficha.</div>`;bindCards()}
function renderCompareBar(){const b=$('#compareBar');b.classList.toggle('show',state.compare.length>0);$('#compareText').textContent=`${state.compare.length}/4 seleccionados`}
function renderAll(){renderStats();renderCatalog();renderQuick();renderOfficialHome();renderCountries();renderRegionChips();renderPlaybooks();renderMaterials();renderStages();renderFavs();renderCompareBar()}
function setup(){fillSelect('#fCat',uniq(RES.map(r=>r.category)),'Todas las categorías');fillSelect('#fType',uniq(RES.map(r=>r.type)),'Todos los tipos');fillSelect('#fRegion',['Global','Latinoamérica','Norteamérica','Europa','Asia','Medio Oriente','África','Oceanía'],'Todas las regiones');fillSelect('#fStage',uniq(RES.map(r=>r.stage)),'Todas las etapas');$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-cat]').forEach(b=>b.onclick=()=>{showView('catalog');state.filters={cat:b.dataset.cat,type:'',region:'',stage:'',scale:''};$('#fCat').value=state.filters.cat;$('#fType').value=$('#fRegion').value=$('#fStage').value=$('#fScale').value='';renderCatalog()});$$('[data-region]').forEach(b=>b.onclick=()=>{showView('catalog');state.filters={cat:'',type:'',region:b.dataset.region,stage:'',scale:''};$('#fRegion').value=state.filters.region;$('#fCat').value=$('#fType').value=$('#fStage').value=$('#fScale').value='';renderCatalog()});$('#search').oninput=e=>{state.search=e.target.value;showView('catalog');renderCatalog()};$('#menuBtn').onclick=()=>$('#side').classList.toggle('open');$('#homeBtn').onclick=()=>showView('dashboard');$('#favBtn').onclick=()=>showView('favorites');$('#compareBtn').onclick=openCompare;$('#compareClear').onclick=()=>{state.compare=[];renderAll()};$('#clearFilters').onclick=()=>{state.filters={cat:'',type:'',region:'',stage:'',scale:''};['#fCat','#fType','#fRegion','#fStage','#fScale'].forEach(s=>$(s).value='');renderCatalog()};$$('[data-preset]').forEach(b=>b.onclick=()=>{const p=b.dataset.preset;$$('[data-preset]').forEach(x=>x.classList.toggle('active',x===b));state.filters.type=p==='oficial'?'Fuente oficial':p==='operativas'?'Herramienta':'';$('#fType').value=state.filters.type;renderCatalog()});$('#modalBack').onclick=e=>{if(e.target.id==='modalBack')closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if(e.key==='/'&&document.activeElement.tagName!=='INPUT'){e.preventDefault();$('#search').focus()}});renderIntents();renderAll()}
setup();
